export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';
export const FETCH_CATEGORY_POSTS = 'FETCH_CATEGORY_POSTS';
export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const POST_VOTE = 'POST_VOTE';
export const DELETE_POST = 'DELETE_POST';
export const EDIT_POST = 'EDIT_POST';
